### PR TITLE
PROJECT: AUTHENTICATION

### PR DESCRIPTION
**Pull request by christianotieno**
Hello reviewer. the following are what we have accomplished in this project and we humbly welcome your review., thank you.

- [x] Basic Setup of the project 
- [x] Sessions and Sign In
- [x] Authentication and Posts

### CODE REVIEW

**Comment by christianotieno** [comment]
As with the linter errors, we can only be certain that the message below is what is causing our errors otherwise the codebase is clean.
```
Error: The `Layout/AlignHash` cop has been renamed to `Layout/HashAlignment`.
(obsolete configuration found in .rubocop.yml, please update it)

```

**Review by Redvanisation — CHANGES_REQUESTED** [review]
# Changes required  ♻️ 

### Hello team  🌟

**Very nice work on this project, however, the following issues need to be fixed before moving on ⬇️** 

- The project is not complete, please the `root` route and add some functionality to the views so the project can be tested properly.

- Fix the linter's errors, the linters files have been updated, check the new version on [here](https://github.com/microverseinc/linters-config).


### _After making the required changes please submit a new code review request_

### Good luck! 🍀

**Review by Redvanisation — CHANGES_REQUESTED** [review]
# Changes required  ♻️ 

### Hello team  🌟

**Very nice work on this project, however, the following issues need to be fixed before moving on ⬇️** 

* [x] User can sign in ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/sign_in_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication))
* [x] As a signed-in user you can create new post ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/signed_in_can_post_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication))
* [x] As a signed-in user you can see post's author ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/signed_in_can_see_author_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication))
* [x] User can sign_out ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/sign_out_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication))
* [x] As a guest you can see only post's text ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/guest_can_see_only_posts_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication))

### _Please implement all of the above in project views._ ⬆️ 

### _After making the required changes please submit a new code review request_

### Good luck! 🍀

**Comment by christianotieno** [comment]
Dear reviewer, we have successfully made the required changes. We hereby welcome your review, thank you.

**Review by maelfosso — APPROVED** [review]
# Congratulations :clap: 

You did it :+1: 
Good luck with the next :smile: 

**Mael FOSSO**
[Github](https://github.com) | [Twitter](https://twitter.com) | [LinkedIn](https://www.linkedin.com/in/mael-elvis-fosso-650b6346/)

**Pull request merged**
